version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myhouse24
    ports:
      - "3307:3306"
  user:
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql