name: Build & Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the project
        run: |
          mvn package -DskipTests=true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: denistp12/myhouse24-user:latest
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo docker stop myhouse24-user-container
            sudo docker rm myhouse24-user-container
            sudo docker rmi denistp12/myhouse24-user
            sudo docker login
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull denistp12/myhouse24-user:latest
            sudo docker run -d --name myhouse24-user-container -p 8089:8080 --network myhouse24da -v myhouse24da:/var/photos denistp12/myhouse24-user